export const TITLE_PAGE = {
  SITE_TITLE: 'Rental Admin',
  NOT_FOUND: 'Không tìm thấy',
  DASHBOARD: 'Dashboard',
  AUTH: {
    LOGIN: 'Đăng nhập',
    FORGOT_PASSWORD: 'Quên mật khẩu',
    RESET_PASSWORD: 'Đặt lại mật khẩu',
  },
  USERS: {
    ROOT: 'Người dùng',
    INDEX: 'Quản lý người dùng',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
    DESCRIPTION: 'Quản lý người dùng hệ thống',
    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm người dùng',
      EDIT: 'Chỉnh sửa',
      RESET_PASSWORD: 'Đổi mật khẩu',
      LOCK: 'Khóa tài khoản',
      ACTIVATE: 'Kích hoạt lại',
      DELETE: 'Xóa người dùng',
      DELETE_MULTI: 'Xoá nhiều người dùng',
    },
    FORM: {
      FULL_NAME: 'Họ và tên',
      FULL_NAME_PLACEHOLDER: 'Nguyễn Văn A',
      EMAIL: 'Email',
      EMAIL_PLACEHOLDER: 'name@rental.local',
      PHONE: 'Số điện thoại',
      PHONE_PLACEHOLDER: '0901234567',
      INITIAL_PASSWORD: 'Mật khẩu ban đầu',
      INITIAL_PASSWORD_PLACEHOLDER: 'Mật khẩu ít nhất 8 ký tự',
      NEW_PASSWORD: 'Mật khẩu mới',
      NEW_PASSWORD_PLACEHOLDER: 'Ít nhất 8 ký tự',
      CONFIRM_NEW_PASSWORD: 'Xác nhận mật khẩu mới',
      CONFIRM_NEW_PASSWORD_PLACEHOLDER: 'Nhập lại mật khẩu mới',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm người dùng mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa thông tin',
      FORM_CREATE_DESCRIPTION: 'Nhập thông tin chi tiết để tạo tài khoản nhân viên hoặc quản trị mới.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật thông tin cơ bản cho tài khoản người dùng này.',
      RESET_PASSWORD_TITLE: 'Đặt lại mật khẩu',
      RESET_PASSWORD_DESCRIPTION_PREFIX: 'Nhập mật khẩu mới cho tài khoản',
      RESET_PASSWORD_DESCRIPTION_SUFFIX: 'Phiên đăng nhập hiện tại sẽ bị hủy.',
      DELETE_TITLE: 'Xác nhận xóa tài khoản',
      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa tài khoản',
      DELETE_DESCRIPTION_SUFFIX: 'Hành động này không thể khôi phục.',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      UPDATE_SUBMIT: 'Cập nhật',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
    ERRORS: {
      CREATE_FAILED: 'Tạo người dùng thất bại',
      UPDATE_FAILED: 'Cập nhật người dùng thất bại',
      RESET_PASSWORD_FAILED: 'Reset mật khẩu thất bại',
    },
  },
  PERMISSIONS: {
    ROOT: 'Quyền',
    INDEX: 'Quản lý quyền',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
  },
  ROLES: {
    ROOT: 'Nhóm quyền',
    INDEX: 'Quản lý nhóm quyền',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
    DESCRIPTION: 'Quản lý nhóm quyền và phân quyền truy cập hệ thống',
    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm nhóm quyền',
      EDIT: 'Chỉnh sửa',
      DELETE: 'Xóa nhóm quyền',
      ASSIGN: 'Gán người dùng',
    },
    FORM: {
      CODE: 'Mã nhóm quyền',
      CODE_PLACEHOLDER: 'POSTMAN_OPERATOR',
      NAME: 'Tên nhóm quyền',
      NAME_PLACEHOLDER: 'Nhóm quyền vận hành',
      DESCRIPTION: 'Mô tả',
      DESCRIPTION_PLACEHOLDER: 'Mô tả phạm vi quyền hạn của nhóm quyền',
      PERMISSIONS: 'Danh sách quyền',
      PERMISSIONS_EMPTY: 'Không có quyền nào phù hợp.',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm nhóm quyền mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa nhóm quyền',
      FORM_CREATE_DESCRIPTION: 'Tạo nhóm quyền tùy chỉnh và chọn các quyền được phép thao tác.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật thông tin và danh sách quyền của nhóm quyền tùy chỉnh.',
      DELETE_TITLE: 'Xác nhận xóa nhóm quyền',
      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa nhóm quyền',
      ASSIGN_TITLE: 'Gán nhóm quyền quản trị',
      ASSIGN_DESCRIPTION: 'Xử lý phần gán nhóm quyền quản trị cho người dùng',
      DELETE_DESCRIPTION_SUFFIX: 'Hành động này không thể khôi phục.',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
    ERRORS: {
      CREATE_FAILED: 'Tạo nhóm quyền thất bại',
      UPDATE_FAILED: 'Cập nhật nhóm quyền thất bại',
      DELETE_FAILED: 'Xóa nhóm quyền thất bại',
    },
  },
} as const;
