export const TITLE_PAGE = {
  SITE_TITLE: 'Rental Admin',
  NOT_FOUND: 'Không tìm thấy',
  DASHBOARD: 'Dashboard',
  AUTH: {
    LOGIN: 'Đăng nhập',
    FORGOT_PASSWORD: 'Quên mật khẩu',
    RESET_PASSWORD: 'Đặt lại mật khẩu',
  },
  AVAILABILITY: {
    ROOT: 'Lịch trống',
    INDEX: 'Kiểm tra lịch trống',
    DESCRIPTION: 'Tìm sản phẩm và thiết bị khả dụng theo khoảng thời gian thuê',
  },
  USERS: {
    ROOT: 'Người dùng',
    INDEX: 'Quản lý người dùng',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
    DESCRIPTION: 'Quản lý người dùng hệ thống',
    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm người dùng',
      EDIT: 'Chỉnh sửa',
      RESET_PASSWORD: 'Đổi mật khẩu',
      LOCK: 'Khóa tài khoản',
      ACTIVATE: 'Kích hoạt lại',
      DELETE: 'Xóa người dùng',
      DELETE_MULTI: 'Xoá nhiều người dùng',
    },
    FORM: {
      FULL_NAME: 'Họ và tên',
      FULL_NAME_PLACEHOLDER: 'Nguyễn Văn A',
      EMAIL: 'Email',
      EMAIL_PLACEHOLDER: 'name@rental.local',
      PHONE: 'Số điện thoại',
      PHONE_PLACEHOLDER: '0901234567',
      INITIAL_PASSWORD: 'Mật khẩu ban đầu',
      INITIAL_PASSWORD_PLACEHOLDER: 'Mật khẩu ít nhất 8 ký tự',
      NEW_PASSWORD: 'Mật khẩu mới',
      NEW_PASSWORD_PLACEHOLDER: 'Ít nhất 8 ký tự',
      CONFIRM_NEW_PASSWORD: 'Xác nhận mật khẩu mới',
      CONFIRM_NEW_PASSWORD_PLACEHOLDER: 'Nhập lại mật khẩu mới',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm người dùng mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa thông tin',
      FORM_CREATE_DESCRIPTION: 'Nhập thông tin chi tiết để tạo tài khoản nhân viên hoặc quản trị mới.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật thông tin cơ bản cho tài khoản người dùng này.',
      RESET_PASSWORD_TITLE: 'Đặt lại mật khẩu',
      RESET_PASSWORD_DESCRIPTION_PREFIX: 'Nhập mật khẩu mới cho tài khoản',
      RESET_PASSWORD_DESCRIPTION_SUFFIX: 'Phiên đăng nhập hiện tại sẽ bị hủy.',
      DELETE_TITLE: 'Xác nhận xóa tài khoản',
      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa tài khoản',
      DELETE_DESCRIPTION_SUFFIX: 'Hành động này không thể khôi phục.',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      UPDATE_SUBMIT: 'Cập nhật',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
    ERRORS: {
      CREATE_FAILED: 'Tạo người dùng thất bại',
      UPDATE_FAILED: 'Cập nhật người dùng thất bại',
      RESET_PASSWORD_FAILED: 'Reset mật khẩu thất bại',
    },
  },
  PRODUCTS: {
    ROOT: 'Sản phẩm',
    INDEX: 'Quản lý sản phẩm',
    DESCRIPTION: 'Quản lý dòng sản phẩm, giá thuê và thông tin bàn giao',
    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm sản phẩm',
      EDIT: 'Chỉnh sửa',
      VIEW_ASSET_UNITS: 'Xem serial',
      DISABLE: 'Tạm tắt',
      ENABLE: 'Bật lại',
      DELETE: 'Xóa',
      DELETE_MULTI: 'Xóa nhiều sản phẩm',
    },
    TABLE: {
      PRODUCT_SKU: 'Sản phẩm / SKU',
      PRODUCT: 'Sản phẩm',
      CATEGORY: 'Danh mục',
      BRAND: 'Thương hiệu',
      ASSET_UNIT_COUNT: 'Số lượng máy',
      DAILY_PRICE: 'Giá ngày',
      DEPOSIT_AMOUNT: 'Tiền cọc',
      STATUS: 'Trạng thái',
      UPDATED_AT: 'Cập nhật',
      ACTIVE: 'Đang hoạt động',
      INACTIVE: 'Tạm tắt',
    },
    FORM: {
      NAME: 'Tên sản phẩm',
      NAME_PLACEHOLDER: 'Sony A7 IV',
      SKU: 'SKU',
      SKU_PLACEHOLDER: 'SONY-A7-IV',
      CATEGORY: 'Danh mục',
      CATEGORY_PLACEHOLDER: 'UUID danh mục',
      BRAND: 'Thương hiệu',
      BRAND_PLACEHOLDER: 'UUID thương hiệu',
      DAILY_PRICE: 'Giá thuê theo ngày',
      HALF_DAY_PRICE: 'Giá thuê theo buổi',
      DEPOSIT_AMOUNT: 'Tiền cọc',
      HOURLY_OVERAGE_PRICE: 'Giá phụ thu thêm theo giờ',
      REPLACEMENT_VALUE: 'Giá trị máy',
      RENTAL_PRICE_TIERS: 'Bậc giá thuê theo ngày',
      RENTAL_PRICE_TIERS_DESCRIPTION: 'Khai báo giá theo số ngày thuê nếu có.',
      RENTAL_PRICE_TIERS_EMPTY: 'Chưa có bậc giá riêng.',
      ADD_PRICE_TIER: 'Thêm bậc',
      MIN_DAYS: 'Từ ngày',
      MAX_DAYS: 'Đến ngày',
      TIER_DAILY_PRICE: 'Giá/ngày',
      TIER_NAME: 'Tên bậc',
      TIER_NAME_PLACEHOLDER: 'Combo 3-6 ngày',
      DESCRIPTION: 'Mô tả',
      DESCRIPTION_PLACEHOLDER: 'Mô tả ngắn về sản phẩm',
      INCLUDED_ACCESSORIES: 'Phụ kiện kèm theo',
      INCLUDED_ACCESSORIES_PLACEHOLDER: 'Body, pin, sạc, thẻ nhớ...',
      USAGE_GUIDE: 'Ghi chú bàn giao',
      USAGE_GUIDE_PLACEHOLDER: 'Kiểm tra pin, format thẻ...',
      IS_ACTIVE: 'Cho phép tạo đơn mới',
      IS_ACTIVE_DESCRIPTION: 'Tắt nếu dòng sản phẩm này tạm ngưng cho thuê.',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm sản phẩm mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa sản phẩm',
      FORM_CREATE_DESCRIPTION: 'Tạo dòng sản phẩm/model cho kho thiết bị.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật thông tin dòng sản phẩm cho thuê.',
      DELETE_TITLE: 'Xác nhận xóa sản phẩm',
      DELETE_SINGLE_PREFIX: 'Bạn có chắc chắn muốn xóa',
      DELETE_MULTI_DESCRIPTION: 'Bạn có chắc chắn muốn xóa {count} sản phẩm?',
      STATUS_ENABLE_TITLE: 'Bật lại sản phẩm',
      STATUS_DISABLE_TITLE: 'Tạm tắt sản phẩm',
      STATUS_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
  },
  ASSET_UNITS: {
    ROOT: 'Thiết bị trong kho',
    INDEX: 'Quản lý thiết bị trong kho',
    DESCRIPTION: 'Quản lý serial, trạng thái và tình trạng từng thiết bị trong kho',
    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm thiết bị',
      EDIT: 'Chỉnh sửa',
      STATUS: 'Cập nhật tình trạng',
      DELETE: 'Xóa',
      DELETE_MULTI: 'Xóa nhiều thiết bị',
    },
    TABLE: {
      SERIAL_PRODUCT: 'Serial / Sản phẩm',
      SERIAL_NUMBER: 'Serial',
      PRODUCT: 'Sản phẩm',
      STATUS: 'Trạng thái',
      CONDITION: 'Tình trạng',
      ACTIVE_STATE: 'Cho thuê',
      UPDATED_AT: 'Cập nhật',
      ACTIVE: 'Đang cho thuê',
      INACTIVE: 'Tạm tắt',
      STATUS_AVAILABLE: 'Sẵn sàng',
      STATUS_MAINTENANCE: 'Bảo trì',
      STATUS_LOST: 'Thất lạc',
      CONDITION_NEW: 'Mới',
      CONDITION_GOOD: 'Tốt',
      CONDITION_FAIR: 'Có hao mòn',
      CONDITION_DAMAGED: 'Hư hỏng',
    },
    FORM: {
      PRODUCT_ID: 'Sản phẩm',
      PRODUCT_ID_PLACEHOLDER: 'Chọn sản phẩm',
      FILTER_PRODUCT: 'Lọc theo sản phẩm',
      FILTER_PRODUCT_PLACEHOLDER: 'Tìm sản phẩm hoặc SKU',
      FILTER_PRODUCT_EMPTY: 'Không tìm thấy sản phẩm',
      FILTER_PRODUCT_CLEAR: 'Bỏ lọc sản phẩm',
      SERIAL_NUMBER: 'Serial',
      SERIAL_NUMBER_PLACEHOLDER: 'SN-A7IV-001',
      STATUS: 'Trạng thái',
      CONDITION: 'Tình trạng',
      NOTE: 'Ghi chú',
      NOTE_PLACEHOLDER: 'Phụ kiện, vết xước, tình trạng thực tế...',
      IS_ACTIVE: 'Cho phép gán vào đơn mới',
      IS_ACTIVE_DESCRIPTION: 'Tắt nếu thiết bị tạm thời không cho thuê.',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm thiết bị vật lý',
      FORM_EDIT_TITLE: 'Chỉnh sửa thiết bị',
      FORM_VIEW_TITLE: 'Chi tiết thiết bị',
      FORM_CREATE_DESCRIPTION: 'Khai báo một serial/thiết bị vật lý thuộc dòng sản phẩm trong kho.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật serial, sản phẩm, trạng thái và ghi chú của thiết bị.',
      FORM_VIEW_DESCRIPTION: 'Xem thông tin serial và tình trạng hiện tại của thiết bị.',
      STATUS_TITLE: 'Cập nhật tình trạng thiết bị',
      STATUS_DESCRIPTION_PREFIX: 'Cập nhật trạng thái, tình trạng và khả năng cho thuê của',
      DELETE_TITLE: 'Xác nhận xóa thiết bị',
      DELETE_SINGLE_PREFIX: 'Bạn có chắc chắn muốn xóa',
      DELETE_MULTI_DESCRIPTION: 'Bạn có chắc chắn muốn xóa {count} thiết bị?',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      CONFIRM_STATUS: 'Cập nhật',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
  },
  PERMISSIONS: {
    ROOT: 'Quyền',
    INDEX: 'Quản lý quyền',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
  },
  ROLES: {
    ROOT: 'Nhóm quyền',
    INDEX: 'Quản lý nhóm quyền',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
    DESCRIPTION: 'Quản lý nhóm quyền và phân quyền truy cập hệ thống',
    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm nhóm quyền',
      EDIT: 'Chỉnh sửa',
      DELETE: 'Xóa nhóm quyền',
      ASSIGN: 'Gán người dùng',
    },
    FORM: {
      CODE: 'Mã nhóm quyền',
      CODE_PLACEHOLDER: 'POSTMAN_OPERATOR',
      NAME: 'Tên nhóm quyền',
      NAME_PLACEHOLDER: 'Nhóm quyền vận hành',
      DESCRIPTION: 'Mô tả',
      DESCRIPTION_PLACEHOLDER: 'Mô tả phạm vi quyền hạn của nhóm quyền',
      PERMISSIONS: 'Danh sách quyền',
      PERMISSIONS_EMPTY: 'Không có quyền nào phù hợp.',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm nhóm quyền mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa nhóm quyền',
      FORM_CREATE_DESCRIPTION: 'Tạo nhóm quyền tùy chỉnh và chọn các quyền được phép thao tác.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật thông tin và danh sách quyền của nhóm quyền tùy chỉnh.',
      DELETE_TITLE: 'Xác nhận xóa nhóm quyền',
      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa nhóm quyền',
      ASSIGN_TITLE: 'Gán nhóm quyền quản trị',
      ASSIGN_DESCRIPTION: 'Xử lý phần gán nhóm quyền quản trị cho người dùng',
      DELETE_DESCRIPTION_SUFFIX: 'Hành động này không thể khôi phục.',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
    ERRORS: {
      CREATE_FAILED: 'Tạo nhóm quyền thất bại',
      UPDATE_FAILED: 'Cập nhật nhóm quyền thất bại',
      DELETE_FAILED: 'Xóa nhóm quyền thất bại',
    },
  },
  CATEGORY: {
    ROOT: 'Danh mục sản phẩm',
    INDEX: 'Quản lý danh mục sản phẩm',
    DESCRIPTION: 'Quản lý nhóm phân loại để tổ chức và lọc các sản phẩm cho thuê',
    ACTIONS: {
      VIEW: 'Xem danh mục',
      CREATE: 'Thêm danh mục',
      EDIT: 'Chỉnh sửa danh mục',
      DELETE: 'Xóa danh mục',
      DELETE_MULTI: 'Xóa nhiều danh mục',
    },
    FORM: {
      NAME: 'Tên danh mục',
      NAME_PLACEHOLDER: 'Máy ảnh mirrorless',
      SLUG: 'Mã định danh',
      SLUG_PLACEHOLDER: 'may-anh-mirrorless',
      IS_ACTIVE: 'Cho phép sử dụng',
      IS_ACTIVE_DESCRIPTION: 'Tắt để không cho chọn trong sản phẩm mới.',
    },
    TABLE: {
      NAME: 'Danh mục',
      PRODUCT_COUNT: 'Số sản phẩm',
      STATUS: 'Trạng thái',
      UPDATED_AT: 'Cập nhật',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm danh mục mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa danh mục',
      FORM_VIEW_TITLE: 'Chi tiết danh mục',
      FORM_CREATE_DESCRIPTION: 'Tạo danh mục mới để gắn cho sản phẩm.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật tên, mã và trạng thái của danh mục.',
      FORM_VIEW_DESCRIPTION: 'Thông tin danh mục đang được sử dụng trong hệ thống.',
      DELETE_TITLE: 'Xác nhận xóa danh mục',
      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa danh mục',
      DELETE_MULTI_DESCRIPTION: 'Bạn có chắc chắn muốn xóa {count} danh mục đã chọn?',
      STATUS_ENABLE_TITLE: 'Bật lại danh mục',
      STATUS_DISABLE_TITLE: 'Tạm tắt danh mục',
      STATUS_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
  },
  BRAND: {
    ROOT: 'Thương hiệu sản phẩm',
    INDEX: 'Quản lý thương hiệu sản phẩm',
    DESCRIPTION: 'Quản lý thương hiệu được sử dụng trong danh mục sản phẩm cho thuê',
    ACTIONS: {
      VIEW: 'Xem thương hiệu',
      CREATE: 'Thêm thương hiệu',
      EDIT: 'Chỉnh sửa thương hiệu',
      DELETE: 'Xóa thương hiệu',
      DELETE_MULTI: 'Xóa nhiều thương hiệu',
    },
    FORM: {
      NAME: 'Tên thương hiệu',
      NAME_PLACEHOLDER: 'Sony',
      SLUG: 'Mã định danh',
      SLUG_PLACEHOLDER: 'sony',
      IS_ACTIVE: 'Cho phép sử dụng',
      IS_ACTIVE_DESCRIPTION: 'Tắt để không cho chọn trong sản phẩm mới.',
    },
    TABLE: {
      NAME: 'Thương hiệu',
      PRODUCT_COUNT: 'Số sản phẩm',
      STATUS: 'Trạng thái',
      UPDATED_AT: 'Cập nhật',
    },
    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm thương hiệu mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa thương hiệu',
      FORM_VIEW_TITLE: 'Chi tiết thương hiệu',
      FORM_CREATE_DESCRIPTION: 'Tạo thương hiệu mới để gắn cho sản phẩm.',
      FORM_EDIT_DESCRIPTION: 'Cập nhật tên, mã và trạng thái của thương hiệu.',
      FORM_VIEW_DESCRIPTION: 'Thông tin thương hiệu đang được sử dụng trong hệ thống.',
      DELETE_TITLE: 'Xác nhận xóa thương hiệu',
      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa thương hiệu',
      DELETE_MULTI_DESCRIPTION: 'Bạn có chắc chắn muốn xóa {count} thương hiệu đã chọn?',
      STATUS_ENABLE_TITLE: 'Bật lại thương hiệu',
      STATUS_DISABLE_TITLE: 'Tạm tắt thương hiệu',
      STATUS_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn',
      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },
  },
  CUSTOMER: {
    ROOT: 'Khách hàng',
    INDEX: 'Quản lý khách hàng',
    CREATE: 'Tạo mới',
    EDIT: 'Cập nhật',
    DESCRIPTION: 'Quản lý thông tin khách hàng',

    ACTIONS: {
      VIEW: 'Xem',
      CREATE: 'Thêm khách hàng',
      EDIT: 'Chỉnh sửa',
      DELETE: 'Xóa khách hàng',
      DELETE_MULTI: 'Xóa nhiều khách hàng',
    },

    FORM: {
      NAME: 'Họ và tên',
      NAME_PLACEHOLDER: 'Nguyễn Văn A',

      PHONE: 'Số điện thoại',
      PHONE_PLACEHOLDER: '0900000000',

      EMAIL: 'Email',
      EMAIL_PLACEHOLDER: 'customer@example.com',

      ADDRESS: 'Địa chỉ',
      ADDRESS_PLACEHOLDER: '123 Nguyễn Trãi, Quận 1, TP.HCM',

      IDENTITY_NUMBER: 'CCCD / CMND',
      IDENTITY_NUMBER_PLACEHOLDER: '079000000001',

      SOCIAL_CONTACT: 'Liên hệ mạng xã hội',
      SOCIAL_CONTACT_PLACEHOLDER: 'zalo.me/0900000000',

      NOTES: 'Ghi chú',
      NOTES_PLACEHOLDER: 'Ghi chú về khách hàng',
    },

    DIALOG: {
      FORM_CREATE_TITLE: 'Thêm khách hàng mới',
      FORM_EDIT_TITLE: 'Chỉnh sửa thông tin',
      FORM_VIEW_TITLE: 'Chi tiết khách hàng',

      FORM_CREATE_DESCRIPTION: 'Nhập thông tin chi tiết để tạo hồ sơ khách hàng mới.',

      FORM_EDIT_DESCRIPTION: 'Cập nhật thông tin cơ bản cho khách hàng này.',

      FORM_VIEW_DESCRIPTION: 'Xem thông tin chi tiết của khách hàng.',

      DELETE_TITLE: 'Xác nhận xóa khách hàng',

      DELETE_DESCRIPTION_PREFIX: 'Bạn có chắc chắn muốn xóa khách hàng',

      DELETE_DESCRIPTION_SUFFIX: 'Hành động này không thể khôi phục.',

      CANCEL: 'Hủy',
      SAVE_CHANGES: 'Lưu thay đổi',
      CREATE_SUBMIT: 'Tạo mới',
      UPDATE_SUBMIT: 'Cập nhật',
      CONFIRM_DELETE: 'Xác nhận xóa',
    },

    ERRORS: {
      CREATE_FAILED: 'Tạo khách hàng thất bại',
      UPDATE_FAILED: 'Cập nhật khách hàng thất bại',
      DELETE_FAILED: 'Xóa khách hàng thất bại',
    },
  },
} as const;
